import {FIELDS,DEFAULTS,COLORS,infernoSettings as values,infernoView,normalizePreset,effectDuration} from './vfx/inferno-settings.js';
const STORAGE='slime.inferno.dome.v1';
export function mountInfernoTuner(parent,lab,{capture,onSeek,onMode}){
 const root=document.createElement('details');root.id='inferno-tuner';parent.append(root);
 root.innerHTML=`<summary>ปรับแต่งลูกไฟ + ระเบิดโดม</summary><p>เปิดเพื่อทดลองภาพแยกจากดาเมจ · ค่าที่บันทึกใช้กับลูกไฟในเกมบนเครื่องนี้</p><div class="row"><button id="tune-start">เปิดตัวปรับ</button><button id="tune-reset">คืนต้นแบบ</button></div><label>แยกชั้น<select id="tune-solo"><option value="all">ทุกชั้น</option><option value="projectile">ลูกไฟ</option><option value="fire">โดมไฟ</option><option value="smoke">ควัน</option><option value="ring">วงกระแทก</option><option value="sparks">สะเก็ด</option><option value="ground">เพลิงคงค้าง</option></select></label><label class="check"><input id="tune-live" type="checkbox" checked>เล่นใหม่เมื่อปรับค่า</label><label class="tune-range">เวลา <output id="tune-time">0.00 s</output><input id="tune-scrub" type="range" min="0" max="2.3" step="0.01" value="0"></label><div id="tune-controls"></div><details><summary>สี</summary><div id="tune-colors"></div></details><div class="row"><button id="tune-save">บันทึก</button><button id="tune-copy">คัดลอกพรีเซ็ต</button></div><details><summary>นำเข้า / ส่งออกพรีเซ็ต</summary><textarea id="tune-json" aria-label="พรีเซ็ต JSON" placeholder="วางพรีเซ็ตที่นี่"></textarea><button id="tune-import">นำเข้าพรีเซ็ต</button></details><a href="/review/index.html">ดูเฟรมที่บันทึกไว้</a><button id="tune-proof">ตรวจ 6 เฟรมจริง</button><output id="tune-status" role="status"></output><div id="tune-frames"></div>`;
 const $=id=>root.querySelector('#'+id),controls=new Map();let live=true,pending=0,editing=false;
 function apply(raw){Object.assign(values,normalizePreset(raw));for(const [k,c] of controls){c.input.value=values[k];c.output.textContent=typeof values[k]==='number'?Number(values[k]).toFixed(2):values[k];}}
 let loaded=false;try{const raw=localStorage.getItem(STORAGE);if(raw){apply(JSON.parse(raw).values??JSON.parse(raw));loaded=true;}}catch{} // Storage may be unavailable in a private session.
 function start(){if(!editing){lab.select(['scatter','burn'].includes(lab.preset)?lab.preset:'inferno');lab.previewMode=true;editing=true;onMode();}lab.paused=false;lab.seek(0);onSeek(0);$('tune-status').textContent='กำลังปรับภาพลูกไฟ · ลากเวลาเพื่อหยุดดู';}
 function changed(){if(!editing)start();Object.assign(values,normalizePreset(values));clearTimeout(pending);if(live&&!lab.paused)pending=setTimeout(()=>{lab.seek(0);onSeek(0);},150);}
 function slider(container,key,title,min,max,step){const label=document.createElement('label');label.className='tune-range';const name=document.createElement('span');name.textContent=title;const output=document.createElement('output'),input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.step=step;input.value=values[key];input.setAttribute('aria-label',title);output.textContent=Number(values[key]).toFixed(2);label.append(name,output,input);container.append(label);controls.set(key,{input,output});input.oninput=()=>{values[key]=Number(input.value);output.textContent=Number(input.value).toFixed(2);changed();};}
 const hints={'สะเก็ดไฟ':'สะเก็ดสกิลจริง · จำนวนและระยะโจมตีตามเลเวลสายสะเก็ด','เพลิงคงค้าง':'เปลวเตี้ยสะบัดเหลื่อมกัน · พื้นที่และเวลาคงอยู่ตามเลเวลสายเพลิง','แถบไฟ 1':'ปรับแถบล่างแยกจากโดม · ซ้ายขวาและหน้าหลังอิงมุมผู้เล่น · ลากเวลาเพื่อหยุดดูขณะปรับ','แถบไฟ 2':'ปรับแถบบนแยกจากโดม · ค่าตำแหน่งย่อขยายตามระเบิด · กดบันทึกเพื่อเก็บทั้งสองแถบ','ลูกไฟ':'ขนาดแกน เปลวพัน และหางสั้นตามทิศบิน','รูปทรง':'ยืดแยกแกน โดยฐานโดมยังติดพื้น','จังหวะ':'ปะทุ → ค้างโดม → เปิดเปลว → จาง','ควัน':'กำหนดเวลาเริ่มหลังชน และเวลาจนสลายแยกจากไฟ · ลดเวลาสลายเพื่อให้ควันหายเร็วขึ้น','รายละเอียด':'ชั้นเสริมสำหรับอ่านแรงกระแทก'};
 for(const group of Object.keys(hints)){const box=document.createElement('details');const title=document.createElement('summary');title.textContent=group;const hint=document.createElement('p');hint.textContent=hints[group];box.append(title,hint);$('tune-controls').append(box);for(const [k,f] of Object.entries(FIELDS))if(f[5]===group&&!['bulge','asymmetry','smokeRoll','shock','sparks'].includes(k))slider(box,k,f[0],f[1],f[2],f[3]);}
 for(const [key,name] of Object.entries({body:'เนื้อไฟ',core:'แกนสว่าง',smokeLight:'ควัน'})){const label=document.createElement('label');label.textContent=name;const input=document.createElement('input');input.type='color';input.value=values[key];input.setAttribute('aria-label',name);const output=document.createElement('output');output.textContent=values[key];label.append(input,output);$('tune-colors').append(label);controls.set(key,{input,output});input.oninput=()=>{values[key]=input.value;output.textContent=input.value;changed();};}
 $('tune-start').onclick=start;$('tune-reset').onclick=()=>{apply({...DEFAULTS,...COLORS});changed();$('tune-status').textContent='คืนต้นแบบโดมแล้ว · กดบันทึกเพื่อเก็บไว้';};$('tune-live').onchange=e=>live=e.target.checked;
 $('tune-solo').onchange=e=>{if(!editing)start();infernoView.solo=e.target.value;if(['sparks','ground'].includes(infernoView.solo)){lab.select(infernoView.solo==='sparks'?'scatter':'burn');onMode();lab.seek(.75);onSeek(.75);}if(lab.elapsed<.42&&infernoView.solo!=='projectile'&&infernoView.solo!=='all'){lab.seek(.75);onSeek(.75);}};
 $('tune-scrub').oninput=e=>{if(!editing)start();lab.paused=true;lab.seek(Number(e.target.value));onSeek(lab.elapsed);};
 const serialize=()=>JSON.stringify({format:'slime-inferno-dome',version:1,values:normalizePreset(values)},null,2);
 $('tune-save').onclick=()=>{try{localStorage.setItem(STORAGE,serialize());$('tune-status').textContent='บันทึกแล้ว · ใช้กับลูกไฟในเกมบนเครื่องนี้';}catch{$('tune-status').textContent='บันทึกในเครื่องไม่ได้ · คัดลอกพรีเซ็ตเก็บแทน';}};
 $('tune-copy').onclick=async()=>{const text=serialize();$('tune-json').value=text;try{await navigator.clipboard.writeText(text);$('tune-status').textContent='คัดลอกพรีเซ็ตแล้ว · ส่งกลับมาให้ฝังเป็นค่าเริ่มต้นได้';}catch{$('tune-json').parentElement.open=true;$('tune-json').focus();$('tune-json').select();$('tune-status').textContent='พรีเซ็ตอยู่ในช่องด้านล่าง เลือกคัดลอกได้';}};
 $('tune-import').onclick=()=>{try{const p=JSON.parse($('tune-json').value);if(p.format&&p.format!=='slime-inferno-dome')throw Error('เป็นพรีเซ็ตคนละสกิล');apply(p.values??p);changed();$('tune-status').textContent='นำเข้าแล้ว · กดบันทึกเพื่อเก็บไว้';}catch(e){$('tune-status').textContent='นำเข้าไม่ได้: '+e.message;}};
 $('tune-proof').onclick=()=>{if(!editing)start();const paused=lab.paused;lab.paused=true;const grid=$('tune-frames');grid.replaceChildren();const t=.42;const frames=[['บิน',.20],['แกนเริ่มระเบิด',t+.012],['ขยายจากแกน',t+values.pop*.32],['โดมเต็ม',t+values.pop+values.hold*.6],['ควันแผ่',t+values.smokeDelay+values.smokeDuration*.35],['จาง',t+values.smokeDelay+values.smokeDuration*.85]];try{for(const [name,age] of frames){const figure=document.createElement('figure'),caption=document.createElement('figcaption');caption.textContent=name+' · '+age.toFixed(2)+' s';figure.append(capture(age),caption);figure.tabIndex=0;figure.setAttribute('role','button');figure.setAttribute('aria-label','ขยายภาพ '+name);const enlarge=()=>{const overlay=document.createElement('div');overlay.className='inferno-frame-view';const close=document.createElement('button');close.textContent='ปิดภาพ';close.onclick=()=>overlay.remove();overlay.append(close,capture(age));document.body.append(overlay);close.focus();};figure.onclick=enlarge;figure.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();enlarge();}};grid.append(figure);}$('tune-status').textContent='6 ภาพจากฉากจริง · คงกล้องและสัดส่วนจอปัจจุบัน';}catch(e){$('tune-status').textContent='ตรวจภาพไม่สำเร็จ: '+e.message;}finally{lab.paused=paused;}};
 $('tune-status').textContent=loaded?'โหลดพรีเซ็ตที่บันทึกไว้แล้ว':'ต้นแบบลูกไฟ B + โดม + ควันแผ่';
 return {sync(){if(!editing)return;$('tune-time').textContent=lab.elapsed.toFixed(2)+' s';$('tune-scrub').max=Math.max(effectDuration(values),lab.combat.stats.groundTime)+.65;$('tune-scrub').value=lab.elapsed;},close(){clearTimeout(pending);editing=false;lab.previewMode=false;infernoView.solo='all';infernoView.mass=-1;$('tune-solo').value='all';}};
}
