import {sunfallSettings as settings,sunfallDefaults,sunfallSpecs,setSunfall,sunfallView} from './vfx/sunfall-settings.js';
export function mountSunfallTuner(panel,lab){
 const box=document.createElement('details');box.id='sunfall-tuner';box.hidden=true;box.innerHTML='<summary>ปรับ Sun Fall</summary><p>ปรับเฉพาะภาพและจังหวะ · ดาเมจและพื้นที่โจมตีคงเดิม</p>';panel.append(box);
 const solo=document.createElement('select');solo.setAttribute('aria-label','แยกชั้น Sun Fall');solo.innerHTML='<option value="all">ทุกชั้น</option><option value="image">ภาพลูกอาทิตย์และระเบิด</option><option value="bands">แถบไฟ 3D เท่านั้น</option><option value="smoke">ควัน 3D เท่านั้น</option>';solo.onchange=()=>{sunfallView.solo=solo.value;lab.restart();};box.append(solo);
 const inputs=new Map();const notice=document.createElement('p');notice.setAttribute('role','status');
 const groups=new Map();for(const[name,title]of [['base','ภาพและจังหวะ'],['fire','แถบไฟ 3D'],['smoke','ควัน 3D']]){const group=document.createElement('details');group.open=name==='base';const summary=document.createElement('summary');summary.textContent=title;group.append(summary);box.append(group);groups.set(name,group);}
 for(const [key,label,min,max,step] of sunfallSpecs){const row=document.createElement('label'),text=document.createElement('span'),input=document.createElement('input');row.className='tune-range';text.textContent=label;input.type='range';Object.assign(input,{min,max,step,value:settings[key]});input.setAttribute('aria-label','Sun Fall '+label);const output=document.createElement('output');output.textContent=settings[key].toFixed(2);row.append(text,output,input);groups.get(key.startsWith('band')?'fire':key.startsWith('smoke')?'smoke':'base').append(row);inputs.set(key,{input,output});input.oninput=()=>{setSunfall({[key]:Number(input.value)});output.textContent=settings[key].toFixed(2);lab.restart();};}
 const save=document.createElement('button');save.textContent='เซฟ Sun Fall';save.onclick=()=>{try{localStorage.setItem('slime.sunfall.v1',JSON.stringify(settings));notice.textContent='บันทึกแล้วในเบราว์เซอร์นี้';}catch{notice.textContent='บันทึกไม่ได้';}};
 const reset=document.createElement('button');reset.textContent='คืนค่า Sun Fall';reset.onclick=()=>{setSunfall(sunfallDefaults);for(const[k,{input,output}]of inputs){input.value=settings[k];output.textContent=settings[k].toFixed(2);}lab.restart();notice.textContent='คืนค่าต้นทางแล้ว · กดเซฟเพื่อเก็บ';};
 const review=document.createElement('a');review.textContent='ตรวจภาพรวม / ควัน / แถบไฟ 3D';review.href='/review/index.html?set=sunfall';review.target='_blank';review.rel='noopener';box.append(save,reset,review,notice);
 return {sync(){box.hidden=lab.preset!=='sun';if(box.hidden){sunfallView.solo='all';solo.value='all';}},close(){sunfallView.solo='all';solo.value='all';}};
}
