/** Runtime-only species/elite integration. The reviewed game/ baseline stays byte-identical. */
export const SPECIES_VERSION='species-exp-elites-v4';
function one(source,label,from,to){
  const count=source.split(from).length-1;
  if(count!==1)throw Error(`${label}: expected one hook, found ${count}`);
  return source.replace(from,to);
}
function replaceBetween(source,label,startMarker,endMarker,replacement){
  const start=source.indexOf(startMarker),end=source.indexOf(endMarker,start);
  if(start<0||end<0)throw Error(`${label}: markers missing`);
  if(source.indexOf(startMarker,start+1)>=0)throw Error(`${label}: start marker not unique`);
  return source.slice(0,start)+replacement+source.slice(end);
}
export function applySpeciesBundle(source){
  source=one(source,'roster path',"from './enemy-roster.js';","from './species/enemy-roster.js';");
  source=one(source,'water path',"from './water-calf.js';","from './species/water-calf.js';");
  source=one(source,'spark path',"from './spark-hedgehog.js';","from './species/spark-hedgehog.js';");
  source=one(source,'turtle path',"import {createPondTurtleRenderer,turtleGuard,turtleDamage,tickTurtleWorld} from './pond-turtle.js';","import {createPondTurtleRenderer,turtleGuard,turtleDamage,tickTurtleWorld,reflectEliteTurtleProjectile} from './species/pond-turtle.js';");
  source=one(source,'critter logic path','from "./critters-v4/logic.js";','from "./species/critters-v4/logic.js";');
  source=one(source,'critter renderer path','from "./critters-v4/renderer.js";','from "./species/critters-v4/renderer.js";');
  source=one(source,'elite frog renderer import',"import {createPondTurtleRenderer,turtleGuard,turtleDamage,tickTurtleWorld,reflectEliteTurtleProjectile} from './species/pond-turtle.js';","import {createPondTurtleRenderer,turtleGuard,turtleDamage,tickTurtleWorld,reflectEliteTurtleProjectile} from './species/pond-turtle.js';\nimport {createEliteFrogRenderer} from './species/elite-frog.js';\nimport {eliteFrogAttack as FElite} from './species/elite-frog-combat.js';");
  source=one(source,'elite frog renderer variable','Br,waterRenderer,sparkRenderer,turtleRenderer,pandaRenderer,Vr','Br,waterRenderer,sparkRenderer,turtleRenderer,pandaRenderer,eliteFrogRenderer,Vr');
  source=one(source,'elite frog renderer init','turtleRenderer=await createPondTurtleRenderer(H,{program:T,geometry:E,uniform:D,render:je});pandaRenderer=await createBambooPandaRenderer(H,{program:T,geometry:E,uniform:D,render:je});Br=await Fe(H);','turtleRenderer=await createPondTurtleRenderer(H,{program:T,geometry:E,uniform:D,render:je});pandaRenderer=await createBambooPandaRenderer(H,{program:T,geometry:E,uniform:D,render:je});eliteFrogRenderer=await createEliteFrogRenderer(H,{program:T,geometry:E,uniform:D,render:je});Br=await Fe(H);');

  const frogBase="function Fl(e){if(e.frogDeath!=null||e.hp<=0||(e.frogAttack||0)>0||!e.frogHopActive)return 0;let t=Math.max(0,Math.min(1,e.frogHopPhase||0));return t<=.18||t>=.92?0:Math.sin((t-.18)/.74*Math.PI)*.30}";
  const frogElite="";
  source=one(source,'frog elite helper',frogBase,frogBase+frogElite);
  source=one(source,'frog elite attack beats hurt pose',"if(e.hit>0)return{r:[.25,.25,.25,.25],w:1,o:0};if((e.frogAttack||0)>0)return{r:[.25,0,.75,.25],w:3,o:1.64};","if(e.hit>0&&!(e.elite&&(e.frogAttack||0)>0))return{r:[.25,.25,.25,.25],w:1,o:0};if((e.frogAttack||0)>0)return{r:[.25,0,.75,.25],w:3,o:1.64};");
  source=one(source,'frog elite shader','uniform float flipX;out vec4 color;void main(){vec2 sampleUV=vec2(flipX>.5?1.-UV.x:UV.x,UV.y);vec2 local=mix(vec2(.004),vec2(.996),sampleUV);vec4 c=texture(atlas,rect.xy+local*rect.zw);if(c.a<.18)discard;vec2 shadowPoint','uniform float flipX,elite;out vec4 color;void main(){vec2 sampleUV=vec2(flipX>.5?1.-UV.x:UV.x,UV.y);vec2 local=mix(vec2(.004),vec2(.996),sampleUV);vec4 c=texture(atlas,rect.xy+local*rect.zw);if(c.a<.18)discard;if(elite>.5){float green=smoothstep(.015,.13,c.g-c.r)*smoothstep(.32,.62,c.g);vec3 accent=vec3(c.r*.78,min(1.,c.g*.96+.025),c.b*.72);c.rgb=mix(c.rgb,accent,.38*green);}vec2 shadowPoint');
  source=one(source,'frog elite uniform',"D(e,i,'flipX',l<0?1:0),e.disable(e.CULL_FACE)","D(e,i,'flipX',l<0?1:0),D(e,i,'elite',t.elite?1:0),e.disable(e.CULL_FACE)");

  source=one(source,'world elite fields','this.pendingHits=[],this.frogDead=[],this.waterDead=[],this.waterSplashes=[],this.sparkDead=[],this.turtleDead=[];resetPandaWorld(this)','this.pendingHits=[],this.eliteFx=[],this.playerPoisonTime=0,this.playerPoisonTick=0,this.playerPoisonDamage=0,this.frogDead=[],this.waterDead=[],this.waterSplashes=[],this.sparkDead=[],this.turtleDead=[];resetPandaWorld(this)');
  source=one(source,'elite effect and poison tick','this.time+=e,this.hurt=Math.max(0,this.hurt-e),this.navClock-=e,','this.time+=e,this.hurt=Math.max(0,this.hurt-e),this.eliteFx??=[],this.eliteFx.forEach(t=>t.age+=e),this.eliteFx=this.eliteFx.filter(e=>e.age<e.life),this.playerPoisonTime>0&&(this.playerPoisonTime=Math.max(0,this.playerPoisonTime-e),this.playerPoisonTick-=e,this.playerPoisonTick<=0&&(this.damage(this.playerPoisonDamage||1),this.playerPoisonTick=.72),this.playerPoisonTime<=0&&(this.playerPoisonDamage=0)),this.navClock-=e,');
  source=one(source,'elite frog no touch melee','n.type!==`spark`&&n.type!==`panda`&&!(n.type===`turtle`&&n.turtleGuardAge!=null)&&s<i.radius','n.type!==`spark`&&n.type!==`panda`&&!(n.type===`thorn`&&n.elite)&&!(n.type===`turtle`&&n.turtleGuardAge!=null)&&s<i.radius');
  source=one(source,'elite frog hop animation','if(n.type===`thorn`&&!n.elite&&!n.boss){','if(n.type===`thorn`&&!n.boss){');
  source=one(source,'elite frog ai','if(n.type===`water`?d=waterRanged(this,n,e,t,s,f,i.damage):n.type===`spark`?d=sparkMelee(this,n,e,t,s,f,i.damage):n.type===`turtle`?d=turtleGuard(this,n,e,t,s,f):n.type===`panda`?d=pandaAI(this,n,e,t,s,f,i.damage):n.windup=0,d){','let frogElite=FElite(this,e,n,s,t,f,i.damage);if(frogElite!==null)d=frogElite;else if(n.type===`water`)d=waterRanged(this,n,e,t,s,f,i.damage);else if(n.type===`spark`)d=sparkMelee(this,n,e,t,s,f,i.damage);else if(n.type===`turtle`)d=turtleGuard(this,n,e,t,s,f);else if(n.type===`panda`)d=pandaAI(this,n,e,t,s,f,i.damage);else n.windup=0;if(d){');
  source=one(source,'elite frog death frame','e.type===`thorn`&&!e.elite&&!e.boss&&this.frogDead.push','e.type===`thorn`&&!e.boss&&this.frogDead.push');
  source=one(source,'boss EXP reduction','var we={name:`Ancient Bloom Colossus`,hp:12e3,speed:.92,radius:2.912,damage:26,xp:56,scale:1.6},Te=eliteRoster;','var we={name:`Ancient Bloom Colossus`,hp:12e3,speed:.92,radius:2.912,damage:26,xp:28,scale:1.6},Te=eliteRoster;');
  source=one(source,'species exp soul','let r=e.xp||{thorn:2,water:10}[e.type]||2,i=this.souls.find(t=>Math.hypot(t.x-e.x,t.z-e.z)<.65);i?i.value+=r:this.souls.push({x:e.x,z:e.z,value:r,age:0,id:++this.serial}),this.effect(`death`,e.x,e.z,.38)','let r=e.xp||{thorn:1,spark:2,turtle:3,water:4,panda:8}[e.type]||1,i=this.souls.find(t=>t.sourceType===e.type&&t.sourceElite===!!e.elite&&Math.hypot(t.x-e.x,t.z-e.z)<.65);i?i.value+=r:this.souls.push({x:e.x,z:e.z,value:r,age:0,id:++this.serial,sourceType:e.type,sourceElite:!!e.elite}),this.effect(`death`,e.x,e.z,.38)');

  source=one(source,'ember reflect','for(let e of t.enemies)if(e.hp>0&&!n.hitIds.has(e.id)&&Math.hypot(e.x-n.x,e.z-n.z)<e.radius+.16&&(this.hit(e,n.s.emberDamage,n.x,n.z,.35),this.burn(e,Math.max(1,Math.round(n.s.burn*.55)),n.s.burnTime*.7),n.hitIds.add(e.id),--n.left<=0)){n.life=0;break}','for(let e of t.enemies)if(e.hp>0&&!n.hitIds.has(e.id)&&Math.hypot(e.x-n.x,e.z-n.z)<e.radius+.16){if(reflectEliteTurtleProjectile(t,e,t.player,n.s.emberDamage)){n.life=0;break}if(this.hit(e,n.s.emberDamage,n.x,n.z,.35),this.burn(e,Math.max(1,Math.round(n.s.burn*.55)),n.s.burnTime*.7),n.hitIds.add(e.id),--n.left<=0){n.life=0;break}}');
  source=one(source,'fireball reflect','n.x=d?d.x:l,n.z=d?d.z:u,(d||s<=c+1e-6)&&(this.explode(t,n.x,n.z,n.s),n.life=0),n.vx=n.x-r,n.vz=n.z-i','n.x=d?d.x:l,n.z=d?d.z:u,d&&reflectEliteTurtleProjectile(t,d.enemy,t.player,n.s.damage)?n.life=0:(d||s<=c+1e-6)&&(this.explode(t,n.x,n.z,n.s),n.life=0),n.vx=n.x-r,n.vz=n.z-i');
  source=one(source,'bolt reflect','if(Math.hypot(t.x-r-o*c,t.z-a-s*c)<t.radius+i.r&&(e.elementalHit(i.family,t,i.damage,i.x,i.z),i.hit.add(t.id),i.family===`frost`&&Et(e,n,t,i.s),i.hit.size>i.pierce)){i.life=0;break}','if(Math.hypot(t.x-r-o*c,t.z-a-s*c)<t.radius+i.r){if(reflectEliteTurtleProjectile(n,t,n.player||r,i.damage)){i.life=0;break}if(e.elementalHit(i.family,t,i.damage,i.x,i.z),i.hit.add(t.id),i.family===`frost`&&Et(e,n,t,i.s),i.hit.size>i.pierce){i.life=0;break}}');
  source=one(source,'render supplied elite frog','if(Br){for(let e of t)if(e.type===\`thorn\`&&!e.elite){let t=Br.draw(e,X,W.player,W.thornFrames,spriteCamera(W.camera));Yn+=t.calls,Xn+=t.triangles}for(let e of J.frogDead||[])if(dr(e.x,e.z,1.4)){let t=Br.draw(e,X,W.player,8,spriteCamera(W.camera));Yn+=t.calls,Xn+=t.triangles}H.useProgram(U)}H.disable(H.BLEND),H.depthMask(!0);','if(Br){for(let e of t)if(e.type===\`thorn\`&&!e.elite){let t=Br.draw(e,X,W.player,W.thornFrames,spriteCamera(W.camera));Yn+=t.calls,Xn+=t.triangles}for(let e of J.frogDead||[])if(!e.elite&&dr(e.x,e.z,1.4)){let t=Br.draw(e,X,W.player,8,spriteCamera(W.camera));Yn+=t.calls,Xn+=t.triangles}H.useProgram(U)}if(eliteFrogRenderer){for(const enemy of t)if(enemy.type===\`thorn\`&&enemy.elite&&dr(enemy.x,enemy.z,2.4)){const drawn=eliteFrogRenderer.draw(enemy,X,W.player,spriteCamera(W.camera));Yn+=drawn.calls;Xn+=drawn.triangles}for(const enemy of J.frogDead||[])if(enemy.elite&&dr(enemy.x,enemy.z,2.4)){const drawn=eliteFrogRenderer.draw(enemy,X,W.player,spriteCamera(W.camera));Yn+=drawn.calls;Xn+=drawn.triangles}H.useProgram(U)}H.disable(H.BLEND),H.depthMask(!0);');

  const feedback='function ci(){let e=B(`combat-feedback`),t=V.clientWidth,n=V.clientHeight;(e.width!==t||e.height!==n)&&(e.width=t,e.height=n);let r=e.getContext(`2d`);r.clearRect(0,0,t,n);let proj=(e,a,o)=>[(X[0]*e+X[4]*a+X[8]*o+X[12]+1)*t/2,(1-(X[1]*e+X[5]*a+X[9]*o+X[13]))*n/2];r.textAlign=`center`,r.font=`bold 18px system-ui`,r.lineWidth=3;for(let e of Y.numbers){let t=.75+e.age*.8,[n,i]=proj(e.x,t,e.z);r.globalAlpha=Math.min(1,(.75-e.age)*4),r.strokeStyle=`#5b301c`,r.fillStyle=`#fff0b9`,r.strokeText(String(Math.round(e.value)),n,i),r.fillText(String(Math.round(e.value)),n,i)}for(let e of J.eliteFx||[]){let a=Math.max(0,1-e.age/e.life);if(e.kind===`frog-cone`)continue;let o=e.r||1,s=[];for(let i=0;i<=28;i++){let c=i/28*Math.PI*2;s.push(proj(e.x+Math.cos(c)*o,.09,e.z+Math.sin(c)*o))}r.beginPath();for(let e=0;e<s.length;e++)e?r.lineTo(s[e][0],s[e][1]):r.moveTo(s[e][0],s[e][1]);r.closePath(),r.lineWidth=e.kind===`spark-ring`?3:2,r.strokeStyle=e.kind===`spark-ring`?`rgba(255,224,91,${.92*a})`:`rgba(144,214,255,${.86*a})`,r.stroke()}}r.globalAlpha=1;for(let e of J.enemies){if(!e.elite||e.hp<=0)continue;let a=({thorn:1.95,spark:1.08,turtle:1.25,water:1.38}[e.type]||1.15)*(e.scale||1),[o,s]=proj(e.x,a,e.z),c=Math.max(66,Math.min(104,74*(e.scale||1))),l=7,u=s-16,d=Math.max(0,Math.min(1,e.hp/Math.max(1,e.maxHP||e.hp)));r.font=`700 12px system-ui`,r.lineWidth=3,r.strokeStyle=`rgba(54,37,26,.9)`,r.fillStyle=`#fff4d7`,r.strokeText(pt(e).name,o,u-5),r.fillText(pt(e).name,o,u-5),r.fillStyle=`rgba(45,31,25,.88)`,r.fillRect(o-c/2-2,u-2,c+4,l+4),r.fillStyle=`#f1dfbb`,r.fillRect(o-c/2,u,c,l),r.fillStyle=d>.35?`#e74e47`:`#d43d3d`,r.fillRect(o-c/2,u,c*d,l),r.strokeStyle=`rgba(86,50,32,.9)`,r.lineWidth=1,r.strokeRect(o-c/2,u,c,l)}r.globalAlpha=1}';
  source=replaceBetween(source,'elite overlay','function ci(){','function li(e){',feedback);
  return source;
}
export function applySpeciesHtml(html){
  return one(html,'manual elite options','<option value="elites">อีลิทที่ใช้งาน · Water Calf</option><option value="elite-water">Water Calf Alpha</option>','<option value="elites">อีลิททั้งหมด · กบ / เม่น / เต่า / ช้าง</option><option value="elite-thorn">Moss Frog Elite</option><option value="elite-spark">Spark Hedgehog Elite</option><option value="elite-turtle">Pond Turtle Elite</option><option value="elite-water">Water Calf Alpha</option>');
}
