import {program,geometry,render,uniform} from '../gl.js';
import {rgb,COLORS} from './inferno-settings.js';
import {atlasAnchors,atlasSizes,atlasDisplaySizes} from './inferno-atlas-data.js';
export const atlasVertex=`layout(location=0) in vec3 position;layout(location=2) in vec2 uv;uniform mat4 vp;uniform vec3 origin,viewDirection;uniform vec2 size;out vec2 UV;void main(){vec3 f=normalize(viewDirection),right=normalize(cross(vec3(0,1,0),f)),up=cross(f,right);UV=uv;vec3 p=origin+right*position.x*size.x+up*position.y*size.y;gl_Position=vp*vec4(p,1.);}`;
export const atlasFragment=`in vec2 UV;uniform sampler2D atlas,betweenAtlas,laterAtlas;uniform vec4 frames;uniform float blendFrames,opacity,solo,halo;uniform vec4 frameScale;uniform vec3 bodyDelta,coreDelta,smokeDelta;out vec4 color;
vec4 sampleFrame(float id,float anchor,vec2 scale){vec2 q=(UV-vec2(.5,.82))*scale+vec2(.5,anchor);if(q.x<.002||q.x>.998||q.y<.002||q.y>.998)return vec4(0);float key=floor(id/3.);vec2 cell=vec2(mod(key,4.),floor(key/4.));vec3 c=mod(id,3.)<.5?texture(atlas,(cell+q)/4.).rgb:(mod(id,3.)<1.5?texture(betweenAtlas,(cell+q)/4.).rgb:texture(laterAtlas,(cell+q)/4.).rgb);float green=max(0.,c.g-max(c.r,c.b));float alpha=1.-smoothstep(.035,.32,green);c.g=min(c.g,max(c.r,c.b));float flame=max(smoothstep(.34,.42,c.r-c.b),smoothstep(.88,.94,c.g)*(1.-smoothstep(.10,.18,abs(q.x-.5)))*step(anchor-.25,q.y));if(id<22.)flame=1.;if(id>=36.)alpha*=1.-flame*smoothstep(36.,45.,id);if(solo>.5&&solo<1.5)alpha*=flame;if(solo>1.5)alpha*=1.-flame;c=mix(c,vec3(1.,.84,.50),(1.-flame)*.30*(1.-smoothstep(.15,.48,abs(q.x-.5)))*(1.-smoothstep(27.,36.,id)));c=clamp(c+mix(smokeDelta,mix(bodyDelta,coreDelta,smoothstep(.45,.9,c.g)),flame),0.,1.);return vec4(c*alpha,alpha);}
void main(){if(halo>.5){float r=length((UV-vec2(.5,.73))/vec2(.53,.48));float a=pow(max(0.,1.-r),2.)*.40*opacity;color=vec4(1.,.78,.28,a);return;}float pick=step(.5,blendFrames);vec4 p=sampleFrame(mix(frames.x,frames.y,pick),mix(frames.z,frames.w,pick),mix(frameScale.xy,frameScale.zw,pick));if(p.a<.025)discard;color=vec4(p.rgb/max(.001,p.a),p.a*opacity);}`;
export function atlasState(age,s){
 const keys=[0,.025,.05,.085,.13,.18,.24,.30,.38,.48,.60,.73,1.05,1.30,1.50,1.65];
 const stages=keys.flatMap((v,i)=>[v,i<15?(v+keys[i+1])*.5:1.72,i<15?v*.25+keys[i+1]*.75:1.755]);
 let t;const end=s.pop+s.hold,release=end+s.breakTime;
 if(age<s.pop)t=.24*Math.pow(Math.max(0,age/s.pop),3.2/s.curve);
 else if(age<end)t=.24+(age-s.pop)/s.hold*.14;
 else if(age<release)t=.38+(age-end)/s.breakTime*.35;
 else t=.73+(age-release)/Math.max(.1,s.duration-release)*1.025;
 let index=0;while(index<47&&t>stages[index+1])index++;
 const next=Math.min(47,index+1),mix=next===index?0:Math.max(0,Math.min(1,(t-stages[index])/(stages[next]-stages[index])));
 return {index,next,mix,opacity:Math.min(1,t/.018)*Math.max(0,Math.min(1,(1.755-t)/.20)),smoke:Math.max(0,Math.min(1,(t-.38)/.7))};
}
export function createAtlasRenderer(gl,texture,betweenTexture,laterTexture){
 const bands=makeFlowBands(gl);
 const p=program(gl,atlasVertex,atlasFragment),g=geometry(gl,[-.5,.82,0,.5,.82,0,.5,-.18,0,-.5,-.18,0],null,[0,0,1,0,1,1,0,1],[0,2,1,0,3,2]);gl.useProgram(p);gl.uniform1i(gl.getUniformLocation(p,'atlas'),6);gl.uniform1i(gl.getUniformLocation(p,'laterAtlas'),8);if(laterTexture){gl.activeTexture(gl.TEXTURE8);gl.bindTexture(gl.TEXTURE_2D,laterTexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.activeTexture(gl.TEXTURE0);}gl.uniform1i(gl.getUniformLocation(p,'betweenAtlas'),7);if(betweenTexture){gl.activeTexture(gl.TEXTURE7);gl.bindTexture(gl.TEXTURE_2D,betweenTexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.activeTexture(gl.TEXTURE0);}if(texture){gl.activeTexture(gl.TEXTURE6);gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.activeTexture(gl.TEXTURE0);}return {draw(f,vp,direction,s,solo){const t=atlasState(f.age,s);if(t.opacity<=0||(f.opacity??1)<=0)return 0;gl.useProgram(p);const a=atlasSizes[t.index],b=atlasSizes[t.next],dims=atlasDisplaySizes[t.index].map((v,i)=>v+(atlasDisplaySizes[t.next][i]-v)*t.mix),scales=[a[0]/dims[0],a[1]/dims[1],b[0]/dims[0],b[1]/dims[1]];const width=f.r*2.3*Math.sqrt(s.width*s.depth)*(1+.40*(1-(1-t.smoke)**2.5)*s.smokeSpread/.88);const height=f.r*2.3*(s.height/.82)*(1+t.smoke*(1.20*s.smokeHeight/.33*s.smokeSize-1));for(const [k,v]of Object.entries({vp,origin:[f.x,.045+t.smoke*t.smoke*s.smokeLift*.2*f.r,f.z],viewDirection:direction,size:[width,height],frames:[t.index,t.next,atlasAnchors[t.index],atlasAnchors[t.next]],bodyDelta:rgb(s.body).map((v,i)=>v-rgb(COLORS.body)[i]),coreDelta:rgb(s.core).map((v,i)=>v-rgb(COLORS.core)[i]),smokeDelta:rgb(s.smokeLight).map((v,i)=>v-rgb(COLORS.smokeLight)[i]),frameScale:scales,blendFrames:t.mix,opacity:t.opacity*(f.opacity??1),solo:solo==='fire'?1:solo==='smoke'?2:0}))uniform(gl,p,k,v);gl.disable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);let glow=0;if(t.index<33&&solo!=='smoke'){uniform(gl,p,'halo',1);render(gl,g);glow=1;}uniform(gl,p,'halo',0);render(gl,g);gl.depthMask(true);gl.disable(gl.BLEND);return 1+glow+(['all','fire'].includes(solo)?bands.draw(f,vp,direction,s):0);}};}

function makeFlowBands(gl){
 const p=program(gl,`layout(location=0)in vec3 position;layout(location=2)in vec2 uv;uniform mat4 vp;uniform vec3 origin,viewDirection;uniform float angle,radius,height,thickness;out vec2 UV;out float front;void main(){float a=position.x+angle;float wave=sin(position.x*5.-angle*1.4)*.055+sin(position.x*9.+angle*2.)*.018;float r=radius*(1.+wave*.35);vec3 q=vec3(cos(a)*r,height+(position.y*thickness+wave)*radius,sin(a)*r);front=dot(normalize(viewDirection.xz),normalize(q.xz));UV=uv;gl_Position=vp*vec4(origin+q,1.);}`,`in vec2 UV;in float front;uniform float opacity,phase;uniform vec3 body,hot;out vec4 color;void main(){if(front<.1)discard;float u=UV.x,v=UV.y;float crest=.77+.12*sin(u*31.-phase*8.)+.07*sin(u*57.-v*3.+phase*6.);float base=.08+.055*sin(u*22.-phase*9.);if(v>crest||v<base)discard;float streak=sin(u*19.-v*7.-phase*12.)*.5+.5;float hotBand=smoothstep(.44,.70,streak)*smoothstep(.18,.42,v);vec3 c=mix(body,hot,hotBand);float a=opacity*smoothstep(.1,.22,front);if(a<.03)discard;color=vec4(c,a);}`);
 const pos=[],uv=[],ix=[];for(let i=0;i<=36;i++){const t=i/36,w=Math.pow(Math.sin(t*Math.PI),.7)*.22;for(const sign of [-1,1]){pos.push(t*2.15,sign*w,0);uv.push(t,(sign+1)/2);}if(i<36){const q=i*2;ix.push(q,q+1,q+2,q+1,q+3,q+2);}}
 const g=geometry(gl,pos,null,uv,ix);
 return {draw(f,vp,dir,s){const end=s.pop+s.hold+s.breakTime*.4,t=f.age;if(t<.06||t>end)return 0;const size=Math.min(1,t/(s.pop+s.hold))**.55,fade=Math.min(1,(t-.06)/.035,(end-t)/.09);gl.useProgram(p);gl.disable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);for(let i=0;i<2;i++){for(const[k,v]of Object.entries({vp,origin:[f.x+f.r*size*((s['bandX'+i]??0)*dir[2]+(s['bandZ'+i]??0)*dir[0])/Math.hypot(dir[0],dir[2]),.03,f.z+f.r*size*(-(s['bandX'+i]??0)*dir[0]+(s['bandZ'+i]??0)*dir[2])/Math.hypot(dir[0],dir[2])],viewDirection:dir,angle:Math.atan2(dir[2],dir[0])-1.075+Math.sin(t*s.flow*9+i*.7)*.24+(i?-.12:.12)+(s['bandAngle'+i]??0)*Math.PI/180,thickness:s['bandThickness'+i]??1,phase:t*s.flow+i*.4,radius:f.r*size*(s['bandRadius'+i]??(i?.65:.85)),height:f.r*size*(s['bandHeight'+i]??(i?1.60:1.10)),opacity:fade,body:rgb(s.body),hot:rgb(s.hot)}))uniform(gl,p,k,v);render(gl,g);}gl.depthMask(true);gl.disable(gl.BLEND);return 2;}};
}

// Independent smoke clock; the fire clock never reads these two controls.
export function smokePlayback(age,s){
 const progress=(age-s.smokeDelay)/s.smokeDuration;
 if(progress<0||progress>=1)return null;
 const onset=s.pop+s.hold*(.34-.24)/.14;
 return {age:onset+(s.duration-onset)*progress,opacity:Math.min(1,progress/.06)};
}
