"""Mechanical shader syntax adapter. Source algorithms remain unchanged."""
from pathlib import Path
import re,json
root=Path(__file__).resolve().parents[1];out={}
for path in sorted((root/'vfx/source').glob('*.gdshader')):
 s=path.read_text();s=re.sub(r'shader_type[^;]+;|render_mode[^;]+;','',s)
 defaults={};types={}
 def uniform(m):
  typ,name,value=m.group(1,2,3);types[name]=typ;value=(value or '0').strip()
  if value.startswith('vec'):
   values=[float(x) for x in value[value.index('(')+1:-1].split(',')];defaults[name]=values*int(typ[-1]) if len(values)==1 else values
  elif typ=='bool':defaults[name]=value=='true'
  else:defaults[name]=float(value)
  return f'uniform {typ} {name};'
 s=re.sub(r'uniform\s+(\w+)\s+(\w+)\s*(?::[^=;]+)?(?:=\s*([^;]+))?;',uniform,s)
 funcs={}
 for name in ['vertex','fragment']:
  m=re.search(r'void\s+'+name+r'\s*\(\)\s*\{',s)
  if not m:funcs[name]='';continue
  begin=m.start();pos=m.end();depth=1
  while depth:
   depth+=(s[pos]=='{')-(s[pos]=='}');pos+=1
  funcs[name]=s[m.end():pos-1];s=s[:begin]+s[pos:]
 vary=re.findall(r'varying\s+(\w+)\s+(\w+)\s*;',s);s=re.sub(r'varying\s+\w+\s+\w+\s*;','',s)
 prefix='precision highp int;\nuniform mat4 vp,model;uniform float clock;uniform vec3 viewDirection;\n#define TIME clock\n#define MODELVIEW_NORMAL_MATRIX mat3(transpose(inverse(model)))\n#define VIEW_MATRIX mat4(1.0)\n'
 vs=prefix+'layout(location=0) in vec3 position;layout(location=1) in vec3 normal;layout(location=2) in vec2 uv;out vec3 portNormal;out vec2 portUV;\n'+''.join(f'out {t} {n};\n' for t,n in vary)+s+'\nvoid main(){vec3 VERTEX=position;vec3 NORMAL=normal;vec2 UV=uv;'+funcs['vertex']+'\nportNormal=normalize(mat3(transpose(inverse(model)))*NORMAL);portUV=uv;gl_Position=vp*model*vec4(VERTEX,1.);}'
 fs=prefix+'in vec3 portNormal;in vec2 portUV;out vec4 portColor;\n#define FRAGCOORD gl_FragCoord\n'+''.join(f'in {t} {n};\n' for t,n in vary)+s+'\nvoid main(){vec3 NORMAL=normalize(portNormal);vec3 VIEW=normalize(viewDirection);vec2 UV=portUV;vec3 ALBEDO=vec3(0.);vec3 EMISSION=vec3(0.);float ALPHA=1.;'+funcs['fragment']+'\nportColor=vec4(ALBEDO+EMISSION,ALPHA);}'
 out[path.stem]={'vs':vs,'fs':fs,'defaults':defaults,'types':types}
(root/'vfx/materials.js').write_text('// Generated by scripts/port-godot-vfx.py from unmodified Godot sources.\nexport const materials='+json.dumps(out)+';\n')
print('Ported',len(out),'original shader programs')
