"""Read terrain art into small gameplay masks; original artwork is unchanged."""
from pathlib import Path
from PIL import Image
import json
root=Path(__file__).resolve().parent.parent
out={}
for name,file in [('north','pond-northern.png'),('clearing','clearing-painted.png')]:
 im=Image.open(root/'public/assets'/file).convert('RGB');rows=[];soil=[]
 for y in range(128):
  row='';dirt=''
  for x in range(128):
   r,g,b=im.getpixel((int((x+.5)*im.width/128),int((y+.5)*im.height/128)))
   visible=min(r,b)-g<20
   row+='1' if visible else '0'
   amount=max(0,min(1,(r-g-2)/13)) if visible else 0
   dirt+=str(round(amount*9))
  rows.append(row);soil.append(dirt)
 out[name]=rows
 if name=='clearing':out['soil']=soil
(root/'zone-masks.js').write_text('// Generated by tools/build-zone-masks.py; occupancy and soil density only.\nexport const ZONE_MASKS='+json.dumps(out,separators=(',',':'))+';\n')
